# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/throwaway4',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/throwaway4',
                'lib_path': 'throwaway4'},
  'syms': {'throwaway4.core': {'throwaway4.core.foo': ('core.html#foo', 'throwaway4/core.py')}}}